update script/create-db-users

diff --git a/script/create-db-users b/script/create-db-users
--- a/script/create-db-users
+++ b/script/create-db-users
@@ -9,33 +9,34 @@ Create the thredded database users for all the supported databases.
 If the `DB` environment variable is set, do the above only for that database.
 HELP
 
+USER='thredded'
+PASS='thredded'
+
 set -e
-log() { if [ -t 1 ]; then echo -e >&2 "${GREEN}$@${RESET_COLOR}"; else echo >&2 "$@"; fi }
+log() { if [ -t 1 ]; then echo -e >&2 "${GREEN}create-db-users: $@${RESET_COLOR}"; else echo >&2 "$@"; fi }
 
 create_mysql_user() {
-  log "\nCreating MySQL thredded user. MySQL root password required.\n"
-  mysql --verbose -uroot -p <<'SQL'
--- This will create a user if one does not exist.
-GRANT ALL PRIVILEGES ON `thredded_gem_dev`.* TO 'thredded'@'localhost' IDENTIFIED BY 'thredded';
-GRANT ALL PRIVILEGES ON `thredded_gem_test`.* TO 'thredded'@'localhost';
+  mysql -s -u"$USER" -p"$PASS" -e '' 2>/dev/null || (\
+    log "Creating MySQL '$USER' user. MySQL root password required." && mysql --verbose -uroot -p <<SQL)
+GRANT ALL PRIVILEGES ON \`thredded_gem_dev\`.* TO '$USER'@'localhost' IDENTIFIED BY '$PASS';
+GRANT ALL PRIVILEGES ON \`thredded_gem_test\`.* TO '$USER'@'localhost';
 SQL
 }
 
 create_postgresql_user() {
-  log "\nCreating Postgres thredded user. Sudo / root required.\n"
-  sudo -u $PG_DAEMON_USER psql --echo-all postgres <<'SQL'
-DO
-$body$
-BEGIN
-   IF NOT EXISTS (SELECT * FROM pg_catalog.pg_user WHERE usename = 'thredded') THEN
-     CREATE ROLE thredded LOGIN PASSWORD 'thredded';
-   END IF;
-   ALTER USER thredded CREATEDB;
-END
-$body$
+  local cmd
+  if [ -n "$PG_DAEMON_USER" ]; then
+    log "sudo required:"
+    cmd="sudo -u $PG_DAEMON_USER psql postgres"
+  else
+    cmd='psql postgres'
+  fi
+  $cmd -tAc "SELECT 1 FROM pg_roles WHERE rolname='$USER'" | grep -q 1 || (\
+    log "Creating Postgres '$USER' user." && $cmd --echo-all <<SQL)
+CREATE ROLE $USER LOGIN PASSWORD '$PASS';
+ALTER USER $USER CREATEDB;
 SQL
 }
 
-[ -z "$PG_DAEMON_USER" ] && PG_DAEMON_USER=postgres
 [ -z "$DB" -o "$DB" = 'mysql2' ] && create_mysql_user
 [ -z "$DB" -o "$DB" = 'postgresql' ] && create_postgresql_user
