Update script/create-db-users

diff --git a/script/create-db-users b/script/create-db-users
--- a/script/create-db-users
+++ b/script/create-db-users
@@ -16,25 +16,25 @@ set -e
 log() { if [ -t 1 ]; then echo -e >&2 "${GREEN}create-db-users: $@${RESET_COLOR}"; else echo >&2 "$@"; fi }
 
 create_mysql_user() {
-  mysql -s -u"$USER" -p"$PASS" -e '' 2>/dev/null || (\
-    log "Creating MySQL '$USER' user. MySQL root password required." && mysql --verbose -uroot -p <<SQL)
+  if mysql -s -u"$USER" -p"$PASS" -e '' 2>/dev/null; then return; fi
+  log "Creating MySQL '$USER' user. MySQL root password required."
+  mysql --verbose -uroot -p <<SQL
 GRANT ALL PRIVILEGES ON \`thredded_gem_dev\`.* TO '$USER'@'localhost' IDENTIFIED BY '$PASS';
 GRANT ALL PRIVILEGES ON \`thredded_gem_test\`.* TO '$USER'@'localhost';
 SQL
 }
 
 create_postgresql_user() {
-  local cmd
-  if [ -n "$PG_DAEMON_USER" ]; then
+  if PGPASSWORD="$PASS" psql -h 127.0.0.1 postgres -U $USER -c ''; then return; fi
+  log "Creating Postgres '$USER' user."
+  local cmd='psql postgres'
+  if ! $cmd -c '' 2>/dev/null; then
     log "sudo required:"
-    cmd="sudo -u $PG_DAEMON_USER psql postgres"
-  else
-    cmd='psql postgres'
+    cmd="sudo -u ${PG_DAEMON_USER:-postgres} psql postgres"
   fi
-  $cmd -tAc "SELECT 1 FROM pg_roles WHERE rolname='$USER'" | grep -q 1 || (\
-    log "Creating Postgres '$USER' user." && $cmd --echo-all <<SQL)
+  $cmd --echo-all <<SQL
 CREATE ROLE $USER LOGIN PASSWORD '$PASS';
-ALTER USER $USER CREATEDB;
+ALTER ROLE $USER CREATEDB;
 SQL
 }
 
