[JRO] Small fixes/optimizations for 2 shell scripts
The create-db-users script does not take into account the fact that the postgresql daemon may be running as another user account on the system so this commit defaults it to `postgres` but allows being overridden by the PG_DAEMON_USER environment variable. This use case is semi-common if a developer is using something like [Postgres.app][] from Heroku.

Both `script/migrate` and `script/create-db-users` were logging out to STDOUT with escape codes that were not being interpreted, so this commit also adds descriptive ENV variables denoting that they will come out colored green.

`database.yml` was defaulting to the postgres port and would not work if using mysql, so pulling those into variables in the yaml file makes it a little easier to discern what the values are that are being set.

Lastly, some accompanying README edits to make things more clear (possible options, etc).

[Postgres.app]: http://postgresapp.com/

diff --git a/script/create-db-users b/script/create-db-users
--- a/script/create-db-users
+++ b/script/create-db-users
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+GREEN='\033[0;32m'
+RESET_COLOR='\033[0m'
+
 if [ -n "$1" ]; then cat <<'HELP'; exit; fi
 Usage: script/create-db-users
 Create the thredded database users for all the supported databases.
@@ -7,10 +10,10 @@ If the `DB` environment variable is set, do the above only for that database.
 HELP
 
 set -e
-log() { if [ -t 1 ]; then echo -e >&2 "\e[0;36m$@\e[0m"; else echo >&2 "$@"; fi }
+log() { if [ -t 1 ]; then echo -e >&2 "${GREEN}$@${RESET_COLOR}"; else echo >&2 "$@"; fi }
 
 create_mysql_user() {
-  log 'Creating MySQL thredded user. MySQL root password required.'
+  log "\nCreating MySQL thredded user. MySQL root password required.\n"
   mysql --verbose -uroot -p <<'SQL'
 -- This will create a user if one does not exist.
 GRANT ALL PRIVILEGES ON `thredded_gem_dev`.* TO 'thredded'@'localhost' IDENTIFIED BY 'thredded';
@@ -19,8 +22,8 @@ SQL
 }
 
 create_postgresql_user() {
-  log 'Creating Postgres thredded user. Sudo / root required.'
-  sudo -u postgres psql --echo-all postgres <<'SQL'
+  log "\nCreating Postgres thredded user. Sudo / root required.\n"
+  sudo -u $PG_DAEMON_USER psql --echo-all postgres <<'SQL'
 DO
 $body$
 BEGIN
@@ -33,5 +36,6 @@ $body$
 SQL
 }
 
+[ -z "$PG_DAEMON_USER" ] && PG_DAEMON_USER=postgres
 [ -z "$DB" -o "$DB" = 'mysql2' ] && create_mysql_user
 [ -z "$DB" -o "$DB" = 'postgresql' ] && create_postgresql_user
